name: Download Day JS

on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点执行

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Latest Version
        id: latest_version
        run: echo "version=$(curl -s https://unpkg.com/dayjs | cut -d'@' -f2)"  >> $GITHUB_OUTPUT
      - name: Download Day JS
        run: |
          curl -sL https://unpkg.com/dayjs -o dayjs.min.js
          mkdir -p dayjs/v${{ steps.latest_version.outputs.version }}
          mv dayjs.min.js dayjs/v${{ steps.latest_version.outputs.version }}
      - name: Commit Files
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update Day JS to v${{ steps.latest_version.outputs.version }}'
          add: 'dayjs/*'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master