name: Download Chart JS

on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点执行

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Latest Version
        id: latest_version
        run: echo "::set-output name=version::$(curl -s https://api.github.com/repos/chartjs/Chart.js/releases/latest | grep 'tag_name' | cut -d\" -f4 | cut -d'v' -f2)"
      - name: Download Chart JS
        run: |
          curl -sL https://github.com/chartjs/Chart.js/releases/download/v${{ steps.latest_version.outputs.version }}/chart.js-${{ steps.latest_version.outputs.version }}.tgz -o chartjs.tgz
          mkdir -p chartjs/v${{ steps.latest_version.outputs.version }}
          tar zxvf chartjs.tgz -C chartjs/v${{ steps.latest_version.outputs.version }}
          rm chartjs.tgz
      - name: Commit Files
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update Chart JS to v${{ steps.latest_version.outputs.version }}'
          add: 'chartjs/*'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
