name: Download D3

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *' # 每天 0 点执行

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Latest Version
        id: latest_version
        run: echo "version=$(curl -s https://api.github.com/repos/d3/d3/releases/latest | grep 'tag_name' | cut -d\" -f4)"  >> $GITHUB_OUTPUT
      - name: Download Bootstrap
        run: |
          curl -sL $(curl -sL https://d3js.org/ | grep -oP 'https://d3js.org.*?\.js') -o d3.v${{ secrets.GITHUB_OUTPUT }}.min.js
          mkdir -p d3
          mv d3.v${{ secrets.GITHUB_OUTPUT }}.min.js d3
      - name: Commit Files
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update D3 to v${{ secrets.GITHUB_OUTPUT }}'
          add: 'd3/*'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master