name: Download Google Fonts

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *' # 每天 0 点执行

jobs:
  download-google-fonts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install gftools
      run: |
        pip install --user gftools
        export PATH=$PATH:~/.local/bin
    - name: Download fonts
      run: |
        mkdir -p fonts/google
        echo "$(gftools --help)"
        echo "=========================================="
        echo "$(gftools add-font --help)"
        echo "=========================================="
        cd fonts
        gftools add-font google --lang CN

    - name: Commit Files
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Downloaded Google Fonts'
        add: 'fonts/*'
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
